apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-configmap
data:
  filebeat.yml: |
    filebeat:
      config:
        modules:
          path: /usr/share/filebeat/modules.d/*.yml
          reload:
            enabled: true
      inputs:
        - type: log
          enabled: true
          paths:
            - /app/logs/*.log
    output.console:
      pretty: true

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-service
spec:
  selector:
    matchLabels:
      app: demo-service
  replicas: 1
  template:
    metadata:
      labels:
        app: demo-service
    spec:
      containers:
        - name: demo-service
          image: huy8895/demo-cicd-github
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_APPLICATION_NAME
              value: k8s-sidecar-demo
            - name: LOGGING_FILE_NAME
              value: /app/logs/app.log

          volumeMounts:
            - name: app-logs
              mountPath: /app/logs
        - name: filebeat-sidecar
          image: docker.elastic.co/beats/filebeat:8.11.3
          volumeMounts:
            - name: app-logs
              mountPath: /app/logs
            - name: filebeat-config
              mountPath: /usr/share/filebeat/filebeat.yml
              subPath: filebeat.yml
      volumes:
        - name: app-logs
          hostPath:
            path: /var/log/demo-hostpath
            type: DirectoryOrCreate
        - name: filebeat-config
          configMap:
            name: filebeat-configmap
            items:
              - key: filebeat.yml
                path: filebeat.yml
---
apiVersion: v1
kind: Service
metadata:
  name: demo-service
spec:
  type: ClusterIP
  selector:
    app: demo-service
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
